version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: shippabledocker/docker-compose.yml:qa
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "49160:8080"
    networks:
      - webnet
networks:
  webnet
