resources:
  - name: github_new_1_test_19
    type: GitRepo
    configuration:
      path: deepikasl/VT2
      gitProvider: deepikaGithub

pipelines:
  - name: pipeline_new_1_test_19
    steps:          
      - name: bash_new_1_test_19
        type: Bash
        configuration:
          inputResources:
            - name: github_new_1_test_19
        execution:
          onExecute:
            - echo "executing bash step..."
  
